global:
  security:
    allowInsecureImages: true

auth:
  username: postgres
  password: postgres

primary:
  initdb:
    scripts:
      00_init_extensions.sql: |
        create extension if not exists pgcrypto;

  service:
    type: NodePort
