# Using Debian-based slim image instead of Alpine because native addons
# (like sodium-native used by @fastify/secure-session) have prebuilt binaries
# for glibc (Debian) but not musl (Alpine), avoiding rebuild issues
FROM node:24.12.0-slim

ENV PNPM_HOME=/home/pnpm
ENV PATH=$PNPM_HOME:$PATH

RUN mkdir $PNPM_HOME
RUN npm i pnpm@10 --location=global

WORKDIR /app

CMD sh -c 'find . -name ".env" -type f -exec mv {} {}.backup-env \;' && pnpm run dev
