FROM node:22-bookworm-slim

RUN apt-get update && apt-get install -y \
    libelf1 \
    libbpf1 \
    build-essential \
    python3 \
    libbpf-dev \
    && rm -rf /var/lib/apt/lists/*

RUN npm i pnpm@10 --location=global

WORKDIR /app

CMD pnpm install && node packages/server/src/index.ts
