image:
  tag: "latest"

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "1024Mi"
    cpu: "500m"

service:
  type: "NodePort"

auth:
  enabled: true
  password: default
